name: verifi

env_file:
  - .lando.env

proxy:
  django:
    - verifi.ap.lfi.site
  mailhog:
    - verifimail.ap.lfi.site

services:
  django:
    type: python:3.11
    build:
      - pip install -U pip
      - pip install pipx
      - pipx install poetry
      - pipx install python-dotenv[cli]
    command: ./.lando.sh

  database:
    type: postgres:12
    portforward: true
    creds:
      database: verifi
      # impossible de changer l'utilisateur et le mdp
      user: postgres
      password:
    config:
      database: verifi
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
    - django

events:
  pre-start:
    - django: poetry install --sync

tooling:
  manage:
    service: django
    cmd: poetry run ./manage.py
