# Generated by Django 5.0.3 on 2024-03-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Electeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code_com",
                    models.CharField(max_length=5, verbose_name="Code INSEE commune"),
                ),
                ("bureau", models.CharField(max_length=10, verbose_name="Bureau")),
                (
                    "num_electeur",
                    models.IntegerField(verbose_name="Numéro dans la liste"),
                ),
                (
                    "type_liste",
                    models.CharField(
                        choices=[
                            ("LP", "Liste principale"),
                            ("LCE", "Liste complémentaire européennes"),
                            ("LCM", "Liste complémentaire municipales"),
                        ],
                        max_length=3,
                        verbose_name="Type de liste",
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "M."), ("F", "Mme.")],
                        max_length=1,
                        verbose_name="Civilité",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom de naissance"),
                ),
                (
                    "nom_usage",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom d'usage"
                    ),
                ),
                ("prenoms", models.CharField(max_length=255, verbose_name="Prénoms")),
                (
                    "date_naissance",
                    models.CharField(max_length=10, verbose_name="Date de naissance"),
                ),
                (
                    "commune_naissance",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ville de naissance"
                    ),
                ),
                (
                    "pays_naissance",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Pays de naissance"
                    ),
                ),
                (
                    "nationalite",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nationalité"
                    ),
                ),
                (
                    "num_voie",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Numéro de voie"
                    ),
                ),
                (
                    "voie",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nom de la voie"
                    ),
                ),
                (
                    "comp1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Complément d'adresse 1",
                    ),
                ),
                (
                    "comp2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Complément d'adresse 2",
                    ),
                ),
                (
                    "lieu_dit",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Lieu-dit"
                    ),
                ),
                (
                    "code_postal",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Code postal"
                    ),
                ),
                (
                    "commune",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ville ou localité"
                    ),
                ),
                (
                    "pays",
                    models.CharField(blank=True, max_length=255, verbose_name="Pays"),
                ),
                ("date_export", models.DateField(verbose_name="Date de l'export")),
            ],
            options={
                "verbose_name": "électeur",
            },
        ),
        migrations.AddConstraint(
            model_name="electeur",
            constraint=models.UniqueConstraint(
                fields=("code_com", "bureau", "type_liste", "num_electeur"),
                name="electeur_unique",
            ),
        ),
    ]
